name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Comment
        run: |
          node -v
          npm -v  
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw-vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexits        
